### PR TITLE
148114171 get single food endpoint

### PR DESCRIPTION
**Pull request by NessEFC**
**WIP branch, do not merge.**

api/v1/foods/:id endpoint is functioning in development, but when I try to access two food records by id in test, I cannot find the second. Attempting to debug the issue. I suspect it's how the test is written. Should also squash commits before merging as well.

### CODE REVIEW

**Comment by NessEFC** [comment]
Also remember to remove pry's and comments where needed.

**Review by ebassity — APPROVED** [review]
Looks great! We'll work on that model test...

**Comment by ebassity** [comment]
@case-eee here's our PR for the endpoints for single food and all foods (we both did them for practice, so you'll see my closed PR also in our PR history). Thanks!

**Comment by case-eee** [comment]
looking good @NessEFC and @somedayrainbows 👍

**Pull request merged**
